config/routes.rb
Footie::Application.routes.draw do
  resources :users do
    resources :predictions
  end

  match '/', :to => 'pages#home'
  match '/signup',  :to => 'games#new'
  match '/edit', :to => 'users#edit'
  match '/new', :to => 'users#new'
  match '/scoreboard', :to => 'users#scoreboard'

  
   resources :masters

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/game.rb
class Game < ActiveRecord::Base
belongs_to :user
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :user
end

app/models/master.rb
class Master < ActiveRecord::Base
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :name

  belongs_to :name, :class_name => "User"
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :predictions, :dependent => :destroy
  accepts_nested_attributes_for :predictions
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @user = User.find(params[:id])
	@game = Game.find(params[:id])
	
  end
  
  def new
  end

  def edit
    @game = Game.find(params[:id])
	@title = "Edit user"
  end
  
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  # GET /masters
  # GET /masters.xml
  def index
      @masters = Master.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @masters }
    end
  end

  # GET /masters/1
  # GET /masters/1.xml
  def show
    @master = Master.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/new
  # GET /masters/new.xml
  def new
    @master = Master.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/1/edit
  def edit
    @master = Master.find(params[:id])
  end

  # POST /masters
  # POST /masters.xml
  def create
    @master = Master.new(params[:master])

    respond_to do |format|
      if @master.save
        format.html { redirect_to(@master, :notice => 'Master was successfully created.') }
        format.xml  { render :xml => @master, :status => :created, :location => @master }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /masters/1
  # PUT /masters/1.xml
  def update
    @master = Master.find(params[:id])

    respond_to do |format|
      if @master.update_attributes(params[:master])
        format.html { redirect_to(@master, :notice => 'Master was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.xml
  def destroy
    @master = Master.find(params[:id])
    @master.destroy

    respond_to do |format|
      format.html { redirect_to(masters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end
  
  def matthew
  @title = "Matthew"
  end

  def mark
  @title = "Mark"
  end
  
  def luke
  @title = "Luke"
  end
  
  def john
  @title = "John"
  end
  
end

app/controllers/predictions_controller - Copy.rb
class PredictionsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @prediction = @user.predictions.create(params[:prediction])
    redirect_to user_path(@user)
  end
  
   def update
    @user = User.find(params[:id])
	@prediction = @user.predictions.create(params[:prediction])
    if @user.update_attributes(params[:prediction])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @prediction = @user.predictions.create(params[:prediction])
    redirect_to user_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
   @users = User.all
   respond_to do |format|
   format.html   # index.html.erb
   format.xml  { render :xml => @users }
   end
end
   

def show
   @user = User.find(params[:id])
   @masteruser = User.find(1)
   @prediction = @user.predictions.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
     
end 

def scoreboard
   @user = User.all
   @masteruser = User.find(1)
   @prediction = Prediction.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
   
     
end 

def score
@score = 0
zz =0
@user.predictions.each do |prediction|
 
     if prediction.home_score =	@masterhomescore[zz].home_score and prediction.away_score = @masterawayscore[zz].away_score
	  then @score = @score + 5
	  zz = zz +1
	  end
  end 
end


#def show
#    user = User.find(params[:id])
#	@users = User.all
#	@predictions = user.predictions
	
#	end
 
def new
  @user = User.new
  respond_to do |format|
	format.html # new.html.erb
	format.xml  { render :xml => @user }
  end
end
 
  
def create
  @user = User.create(params[:user])
  13.times do
  @prediction = @user.predictions.create(params[:prediction])
  end
   
  respond_to do |format|
  if @user.save
  format.html { redirect_to(@user,
				:notice => 'Welcome new user.') }
  format.xml  { render :xml => @user,
				:status => :created, :location => @user }
  else
    format.html { render :action => "new" }
	format.xml  { render :xml => @user.errors,
				:status => :unprocessable_entity }
   end
  end
end 

  
def edit
   @user = User.find(params[:id])
   @masteruser = User.find(1)
   @prediction = @user.predictions.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
   
end
  
 def update
  @user = User.find(params[:id])
  @user.update_attributes(params[:user]) ?
    redirect_to(user_path(@user)) : render(:action => :edit)
  end
  
  def destroy
  User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path#/
  end 

 
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<%= @game.name %>
<%= @game.home %>
<%= @game.home_score %>
<%= @game.away %>
<%= @game.away_score %>

app/views/masters/_form.html.erb
<%= form_for(@master) do |f| %>
  <% if @master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
      <% @master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :homescore %><br />
    <%= f.text_field :homescore %>
  </div>
  <div class="field">
    <%= f.label :away %><br />
    <%= f.text_field :away %>
  </div>
  <div class="field">
    <%= f.label :awayscore %><br />
    <%= f.text_field :awayscore %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/masters/edit.html.erb
<h1>Editing master</h1>

<%= render 'form' %>

<%= link_to 'Show', @master %> |
<%= link_to 'Back', masters_path %>

app/views/masters/index.html.erb
<h1>Listing masters</h1>

<table>
  <tr>
    <th>Home</th>
    <th>Homescore</th>
    <th>Away</th>
    <th>Awayscore</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @masters.each do |master| %>
  <tr>
    <td><%= master.home %></td>
    <td><%= master.homescore %></td>
    <td><%= master.away %></td>
    <td><%= master.awayscore %></td>
    <td><%= link_to 'Show', master %></td>
    <td><%= link_to 'Edit', edit_master_path(master) %></td>
    <td><%= link_to 'Destroy', master, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Master', new_master_path %>

app/views/masters/new.html.erb
<h1>New master</h1>

<%= render 'form' %>

<%= link_to 'Back', masters_path %>

app/views/masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Home:</b>
  <%= @master.home %>
</p>

<p>
  <b>Homescore:</b>
  <%= @master.homescore %>
</p>

<p>
  <b>Away:</b>
  <%= @master.away %>
</p>

<p>
  <b>Awayscore:</b>
  <%= @master.awayscore %>
</p>


<%= link_to 'Edit', edit_master_path(@master) %> |
<%= link_to 'Back', masters_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
  <% end %>

  <div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </div>

  <div class="actions">
  <%= f.submit %>
  </div>
  <% end %> 

app/views/users/_score.html.erb
<% score = 0 %>
<% zz =0 %>
<% @user.predictions do |prediction| %>
 
    <% if prediction.home_score =	@masterhomescore[zz].home_score and prediction.away_score = @masterawayscore[zz].away_score %>
	 <% then score = score + 5 %>
	 <% zz = zz +1 %>
	 <% end %>
<% end %>
<% score %>

app/views/users/edit.html.erb
<h1>Edit user</h1>


<table>
  <tr>
    <th>Home</th>
    <th>Home Score</th>
    <th>Away</th>
    <th>Away Score</th>
    <th></th>
  </tr>
</table>

<table>
<% @users.each do |prediction| %>
  <tr>
    <td><%= prediction.home %></td>
    <td><%= prediction.home_score %></td>
	<td><%= prediction.away %></td>
    <td><%= prediction.away_score %></td>

      </tr>
<% end %>
</table>

<%= form_for(@user) do |f| %>
   <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br />
    <%= f.text_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away %><br />
    <%= f.password_field :away %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br />
    <%= f.password_field :away_score %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/form.html.erb
<h2>Comments</h2>

  <%= form_for([@user, @user.predictions.build]) do |f| %>

  <div class="field">
	<%= f.label :home %><br /> 
	<%= f.text_field :home %>
	</div>
	<div class="field">
	<%= f.label :home_score %><br />
	<%= f.text_field :home_score %>
	</div>
	<div class="field">
	<%= f.label :away %><br />
	<%= f.text_field :away %>
	</div>
	<div class="field">
	<%= f.label :away_score %><br />
	<%= f.text_field :away_score %>
	</div>
	<div class="actions">
	<%= f.submit %>
	</div>
<% end %> 





<h2>Add a comment:</h2>
  <%= form_for([@user, @user.predictions.build]) do |f| %>
    <div class="field">
	<%= f.label :home %><br />
	<%= f.text_field :home %>
	</div>
	<div class="field">
	<%= f.label :home_score %><br />
	<%= f.text_area :home_score %>
	</div>
	<div class="field">
	<%= f.label :away %><br />
	<%= f.text_area :away %>
	</div>
	<div class="field">
	<%= f.label :away_score %><br />
	<%= f.text_area :away_score %>
	</div>
	<div class="actions">
	<%= f.submit %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Home Page</h1>
<li>Welcome to the game. See if you can get the greatest number of correct</li>
<li> predictions of this week's premiership games.</li>
<li>It's 2 points for predicting correct winner (or draw) </li>
<li> and an extra 3 points for correct score </li>


<h1>What next</h1>

<li>From here you can use the links to access an existing user (No amending anyone else's, please) </li>
<li> or create a new users. This week's fixtures should be pready for you to predict. Have fun... </li>

app/views/users/luke.html.erb
<h1>Luke Page</h1>
<p>Luke's scores</p>

app/views/users/mark.html.erb
<h1Mark Page</h1>
<p>Mark's scores</p>

app/views/users/matthew.html.erb
<h1>Matthew Page</h1>
<p>Matthew's scores</p>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>
<li></li>

<p>Create a new user here... Then be ready to make your predictions!</p>

<%= link_to 'Back', users_path %>

app/views/users/predictionloop.html.erb
<% @user.each do |user| %>
  <% yy = 0 %>
  <tr></tr>
  <%= "user"  %><%= uu %>
  <%= @user[uu].name %>
    <% @prediction.each do |prediction| %>
	
    <% unless @prediction[zz].home_score == nil or @prediction[zz].away_score == nil or @masterhomescore[yy].home_score == nil or @masterawayscore[yy].away_score == nil%> 
      <% if (@prediction[zz].home_score == @prediction[zz].away_score) and (@masterhomescore[yy].home_score == @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score > @prediction[zz].away_score) and (@masterhomescore[yy].home_score > @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score < @prediction[zz].away_score) and (@masterhomescore[yy].home_score < @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score  == @masterhomescore[yy].home_score) and ( @prediction[zz].away_score == @masterawayscore[yy].away_score) then scoreplus = scoreplus + 3 %>
      <% end %>
	
	    
      <%= @prediction[zz].user_id %>
      <%= @prediction[zz].home_score %>
      <%= @prediction[zz].away_score%>
      <%= @masterhomescore[yy].home_score%>
      <%= @masterawayscore[yy].away_score%>
      <%= scoreplus%>
      <% yy = yy +1 %>	
      <% zz = zz + 1 %>
    <% end %>
    
  <% end %>
  <%uu = uu +1 %>
  <tr></tr>
<% end %>

app/views/users/scoreboard.html.erb
<p class="notice"><%= notice %></p>

<% score = 0 %>
<% scoreboard = Hash.new %>
<% sortscore = Hash.new %>
<% scoreplus = 0 %>
<% uu = 0 %>
<% yy = 0 %>
<% zz =0 %>

<% @user.count.times do %>
  <% yy = 0 %>
  <tr></tr>
  <% 13.times do %>
	
    <% unless @prediction[zz].home_score == nil or @prediction[zz].away_score == nil or @masterhomescore[yy].home_score == nil or @masterawayscore[yy].away_score == nil%> 
      <% if (@prediction[zz].home_score == @prediction[zz].away_score) and (@masterhomescore[yy].home_score == @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score > @prediction[zz].away_score) and (@masterhomescore[yy].home_score > @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score < @prediction[zz].away_score) and (@masterhomescore[yy].home_score < @masterawayscore[yy].away_score) then scoreplus = scoreplus + 2 %>
      <% end %>
	
	  <% if (@prediction[zz].home_score  == @masterhomescore[yy].home_score) and ( @prediction[zz].away_score == @masterawayscore[yy].away_score) then scoreplus = scoreplus + 3 %>
      <% end %>
		       
    <% end %>
    <% yy = yy +1 %>	
    <% zz = zz + 1 %>
  
  <% end %>
  <% scoreboard[@user[uu].name] = scoreplus %>
  <% scoreplus = 0 %>
  <% uu = uu +1 %>
  <tr></tr>
<% end %>

<% sortscore = scoreboard.sort_by {|key, value| -value} %>

<table>

  <tr>
    <th>Player</th>
    <th>Score</th>
  </tr>

  <% sc = 0 %>
  <% ((@user.count)-1).times do %>
    <tr>
    <% sc = sc +1 %>
	<td><%= player = (sortscore[sc])[0] %></td>
	<td><%= score = (sortscore[sc])[1] %></td>
	</tr>
  <% end %>


</table>
				
<h2> THIS WEEK'S WINNER IS <%= (sortscore[1])[0] %> </h2>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>


<h2><%= @user.name %>'s predictions </h2>
 
  <table>
  <tr>
    <th>Home</th>
    <th>Home Score</th>
    <th>Away Score</th>
	<th>Away</th>
	<th>Prediction</th>
    <th></th>
  </tr>


<% score = 0 %>
<% zz =0 %>
<% @user.predictions.each do |prediction| %>

  <% scoreplus = 0 %>
  
  <% unless prediction.home_score == nil or @masterhomescore[zz].home_score == nil or prediction.away_score == nil or @masterawayscore[zz].away_score == nil %>
    <% if (prediction.home_score == prediction.away_score) and (@masterhomescore[zz].home_score == @masterawayscore[zz].away_score) then scoreplus = scoreplus + 2 %>
    <% end %>
  
    <% if (prediction.home_score > prediction.away_score) and (@masterhomescore[zz].home_score > @masterawayscore[zz].away_score)then scoreplus = scoreplus + 2 %>
    <% end %>
	
	<% if (prediction.home_score < prediction.away_score) and (@masterhomescore[zz].home_score < @masterawayscore[zz].away_score)then scoreplus = scoreplus + 2 %>
    <% end %>
	
	<% if (prediction.home_score == @masterhomescore[zz].home_score ) and (prediction.away_score == @masterawayscore[zz].away_score) then scoreplus = scoreplus + 3 %>
    <% end %>
  
  
  <tr>
  <% unless (@masterhome[zz].home == nil) %>
  <td><%= @masterhome[zz].home %></td>
  <td><%= prediction.home_score %></td>
  <td><%= prediction.away_score %></td>
  <td><%= @masteraway[zz].away %></td>
  <td><%= scoreplus %></td>
  <% end %>
  <% end %>
  </tr>
 
  <% score = score + scoreplus %>
  <% zz = zz +1 %>

<% end %>	
</table>


				
				<h3><%= link_to "edit predictions", edit_user_path(@user) %></h3>
				
<h2>YOUR SCORE IS <%= score %> </h2>

app/views/users/show1.html.erb
<p class="notice"><%= notice %></p>

<table>
  <tr>
    <th>Home</th>
    <th>Home Score</th>
    <th>Away</th>
    <th>Away Score</th>
    <th></th>
  </tr>

<% @user.predictions.each do |prediction| %>
  <tr>
    <td><%= prediction.home %></td>
    <td><%= prediction.home_score %></td>
	<td><%= prediction.away %></td>
    <td><%= prediction.away_score %></td>
  </tr>
<% end %>
</table>



<h2><%= @user.name %>'s predictions</h2>
  <table>
  <tr>
    <th>Home</th>
    <th>Home Score</th>
    <th>Away</th>
    <th>Away Score</th>
    <th></th>
  </tr>


  
    <%= form_for([@user, @user.predictions.build]) do |f| %>
  <% @user.predictions.each do |prediction| %>

  <tr>
  <div class="field">
   <td><%= f.text_field :home %></td>
  </div>
  
  <div class="field">
   <td><%= f.text_field :home_score %></td>
  </div>
  
  <div class="field">
   <td><%= f.text_field :away %></td>
  </div>
  
  <div class="field">
   <td><%= f.text_field :away_score %></td>
  </div>
  </tr>
 <% end %> 
  </table>
   
	<div class="actions">
	<%= f.submit %>
	</div>
	
<% end %> 

app/views/users/show_working.html.erb
<p class="notice"><%= notice %></p>


<% score = 0 %>
<% zz =0 %>
<% @user.predictions.each do |prediction| %>
 
    <% if prediction.home_score =	@masterhomescore[zz].home_score and prediction.away_score = @masterawayscore[zz].away_score %>
	 <% then score = score + 5 %>
	 <% zz = zz +1 %>
	 <% end %>
<% end %>
<% score %>





<h2><%= @user.name %>'s predictions -- YOUR SCORE IS <%= score %></h2>
 
  <table>
  <tr>
    <th>Home</th>
    <th>Home Score</th>
        <th>Away Score</th>
	<th>Away</th>
    <th></th>
  </tr>

<% hh = [] %>
<% aa = [] %>
<% x = 12 %>  
<% 13.times do %>
  <% hh << @masterhome[x].home %>
  <% aa << @masteraway[x].away %>
  <% x = x - 1 %>
 <% end %> 
 
 
 <%= form_for @user do |f| %>
  <%= f.fields_for :predictions do |p| %>
  
  
    	 
    <tr>
    <td><%=  hh.pop %></td>
	<td><%= p.text_field :home_score %></td>
    <td><%= p.text_field :away_score %></td>
	<td><%= aa.pop %></td>
 	</tr>
	<tr></tr>
		
	  	
	<% end %>
	</table>
	
    <%= submit_tag %>


	
	      
<% end %>

 