config/routes.rb
Footie::Application.routes.draw do
  resources :users do
    resources :predictions
  end

  match '/', :to => 'pages#home'
  match '/signup',  :to => 'games#new'
  match '/edit', :to => 'users#edit'
  match '/new', :to => 'users#new'
  match '/scoreboard', :to => 'users#scoreboard'

  
   resources :masters

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/game.rb
class Game < ActiveRecord::Base
belongs_to :user
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :user
end

app/models/master.rb
class Master < ActiveRecord::Base
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :name

  belongs_to :name, :class_name => "User"
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :predictions, :dependent => :destroy
  accepts_nested_attributes_for :predictions
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @user = User.find(params[:id])
	@game = Game.find(params[:id])
	
  end
  
  def new
  end

  def edit
    @game = Game.find(params[:id])
	@title = "Edit user"
  end
  
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  # GET /masters
  # GET /masters.xml
  def index
      @masters = Master.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @masters }
    end
  end

  # GET /masters/1
  # GET /masters/1.xml
  def show
    @master = Master.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/new
  # GET /masters/new.xml
  def new
    @master = Master.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/1/edit
  def edit
    @master = Master.find(params[:id])
  end

  # POST /masters
  # POST /masters.xml
  def create
    @master = Master.new(params[:master])

    respond_to do |format|
      if @master.save
        format.html { redirect_to(@master, :notice => 'Master was successfully created.') }
        format.xml  { render :xml => @master, :status => :created, :location => @master }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /masters/1
  # PUT /masters/1.xml
  def update
    @master = Master.find(params[:id])

    respond_to do |format|
      if @master.update_attributes(params[:master])
        format.html { redirect_to(@master, :notice => 'Master was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.xml
  def destroy
    @master = Master.find(params[:id])
    @master.destroy

    respond_to do |format|
      format.html { redirect_to(masters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end
  
  def matthew
  @title = "Matthew"
  end

  def mark
  @title = "Mark"
  end
  
  def luke
  @title = "Luke"
  end
  
  def john
  @title = "John"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
   @users = User.all
   respond_to do |format|
   format.html   # index.html.erb
   format.xml  { render :xml => @users }
   end
end
   

def show
   @user = User.find(params[:id])
   @masteruser = User.find(1)
   @prediction = @user.predictions.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
     
end 

def scoreboard
   @user = User.all
   @masteruser = User.find(1)
   @prediction = Prediction.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
   
     
end 

def score
@score = 0
zz =0
@user.predictions.each do |prediction|
 
     if prediction.home_score =	@masterhomescore[zz].home_score and prediction.away_score = @masterawayscore[zz].away_score
	  then @score = @score + 5
	  zz = zz +1
	  end
  end 
end


#def show
#    user = User.find(params[:id])
#	@users = User.all
#	@predictions = user.predictions
	
#	end
 
def new
  @user = User.new
  respond_to do |format|
	format.html # new.html.erb
	format.xml  { render :xml => @user }
  end
end
 
  
def create
  @user = User.create(params[:user])
  13.times do
  @prediction = @user.predictions.create(params[:prediction])
  end
   
  respond_to do |format|
  if @user.save
  format.html { redirect_to(@user,
				:notice => 'Welcome new user.') }
  format.xml  { render :xml => @user,
				:status => :created, :location => @user }
  else
    format.html { render :action => "new" }
	format.xml  { render :xml => @user.errors,
				:status => :unprocessable_entity }
   end
  end
end 

  
def edit
   @user = User.find(params[:id])
   @masteruser = User.find(1)
   @prediction = @user.predictions.all
   @master = Prediction.where(:user_id => 1)
   @masterhome = @master.select("home")
   @masterhomescore = @master.select("home_score")
   @masteraway = @master.select("away")
   @masterawayscore = @master.select("away_score")
   
end
  
 def update
  @user = User.find(params[:id])
  @user.update_attributes(params[:user]) ?
    redirect_to(user_path(@user)) : render(:action => :edit)
  end
  
  def destroy
  User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path#/
  end 

 
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prediction site | <%= @title%>  page </title>
    <%= csrf_meta_tag %>
	<%= javascript_include_tag :defaults %>
	<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
     <%= stylesheet_link_tag 'custom', :media => 'screen' %> 
  </head>
  <body>
      
      <header>
        <%= image_tag("soccer.png", :alt => "Sample App", :class => "round") %>
      </header>
  
	    <nav>	
		  
            <h3>Users </h3>
			<ul class="links">
              <li><%= link_to "Home", users_path %></li>
			  <% unless @users.nil? %>
			    <% @users.each do |user| %>	
			      <li><%= link_to user.name, user %>
				   <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
								
					
				<% end %>
				
				
			  <h3>New User</h3>
			  <li><%= link_to "New", new_path %></li>
			  
			  <h3>Scoreboard</h3>
			  <li><%= link_to "Scoreboard", scoreboard_path %></li>
			   
			  
			  <% end %>			  
            </ul>
	    </nav>
      
        <h1>Matthew's predictomatic website</h1>  
             
      <section class="round">
        <%= yield %>
      </section>
	  
<%#= debug(params) if Rails.env.development? %>
   
  </body>
</html>

app/views/layouts/original_application.html.erb
    <style type="text/css" media="screen">
      body {
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #006600;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #900;
      }

      h1 {
        font-size: 20px;
        color: #000;
      }

      a  {color: #03c}
      a:hover {
        background-color: #03c;
        color: white;
        text-decoration: none;
      }


      #page {
        background-color: #00f0f0;
        width: 750px;
        margin: 0;
        margin-left: auto;
        margin-right: auto;
      }

      #content {
        float: left;
        background-color: #060;
        border: 3px solid #fff;
        border-top: none;
        padding: 25px;
        width: 500px;
      }

      #sidebar {
        float: right;
        width: 150px;
      }

      #footer {
        clear: both;
      }


      #header, #about, #getting-started {
        padding-left: 130px;
        padding-right: 30px;
      }


      #header {
        background-image: url("images/soccer.png");
        background-repeat: no-repeat;
        background-position: top left;
        height: 75px;
      }
      #header h1, #header h2 {margin: 0}
      #header h2 {
        color: #fff;
        font-weight: normal;
        font-size: 20px;
      }


      #about h3 {
        margin: 0;
        margin-bottom: 10px;
        font-size: 20;
      }

      #about-content {
        background-color: #ffd;
        border: 1px solid #fc0;
        margin-left: -55px;
        margin-right: -10px;
      }
      #about-content table {
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 10px;
        border-collapse: collapse;
      }
      #about-content td {
        padding: 10px;
        padding-top: 3px;
        padding-bottom: 3px;
      }
      #about-content td.name  {color: #555}
      #about-content td.value {color: #000}

      #about-content ul {
        padding: 0;
        list-style-type: none;
      }

      #about-content.failure {
        background-color: #fcc;
        border: 1px solid #f00;
      }
      #about-content.failure p {
        margin: 0;
        padding: 10px;
      }


      #getting-started {
        border-top: 1px solid #c00;
        margin-top: 25px;
        padding-top: 15px;
      }
      #getting-started h1 {
        margin: 0;
        font-size: 30px;
      }
      #getting-started h2 {
        margin: 0;
        font-size: 14px;
        font-weight: normal;
        color: #333;
        margin-bottom: 25px;
      }
      #getting-started ol {
        margin-left: 0;
        padding-left: 0;
      }
      #getting-started li {
        font-size: 18px;
        color: #fff;
        margin-bottom: 25px;
      }
      #getting-started li h2 {
        margin: 0;
        font-weight: normal;
        font-size: 18px;
        color: #fff;
      }
      #getting-started li p {
        color: #fff;
        font-size: 13px;
      }


      #sidebar ul {
        margin-left: 0;
        padding-left: 0;
      }
      #sidebar ul h3 {
        margin-top: 25px;
        font-size: 15px;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
      }
      #sidebar li {
        list-style-type: none;
      }
      #sidebar ul.links li {
        margin-bottom: 5px;
      }

    </style>
    <script type="text/javascript">
      function about() {
        info = document.getElementById('about-content');
        if (window.XMLHttpRequest)
          { xhr = new XMLHttpRequest(); }
        else
          { xhr = new ActiveXObject("Microsoft.XMLHTTP"); }
        xhr.open("GET","rails/info/properties",false);
        xhr.send("");
        info.innerHTML = xhr.responseText;
        info.style.display = 'block'
      }
    </script>
  </head>
  <body>
    <div id="page">
      <div id="sidebar">
        <ul id="sidebar-items">
          <li>
            <h3>Users</h3>
            <ul class="links">
               #
			   #
               #			   
            </ul>
          </li>
        </ul>
      </div>

      <div id="content">
        <div id="header">
          <h1>Matthew's Football Predictions</h1>
          <h2>This week's scores</h2>
        </div>

        <div id="about">
          <h3><%= yield%></h3>
          <div id="about-content" style="display: none"></div>
        </div>

        <div id="getting-started">
          <h1>Predictions</h1>
          <h2>1,2,3</h2>

          <ol>
            <li>
              <h2>Game 1</h2>
              <p>1-2</p>
            </li>

            <li>
              <h2>Game 2</h2>
              <p>2-0</p>
            </li>

            <li>
              <h2>Game 3</h2>
              <p>10-10</p>
            </li>
          </ol>
        </div>
      </div>

      <div id="footer">&nbsp;</div>
    </div>
  </body>
</html>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/about.html.erb
<h1>About Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<h1>Master Scores Page</h1>
<p> Master Scores</p>
         
     

app/views/pages/mark.html.erb
<h1>Mark Page</h1>
<p>Mark's scores</p>

app/views/pages/mattyhew.html.erb
<h1>Matthew Page</h1>
<p>Matthew's scores</p>